//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperHandbook.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public Equipment()
        {
            this.EquipPowers = new HashSet<EquipPower>();
            this.SuperEquips = new HashSet<SuperEquip>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Origin { get; set; }
        public Nullable<int> ListId { get; set; }
    
        public virtual ICollection<EquipPower> EquipPowers { get; set; }
        public virtual ICollection<SuperEquip> SuperEquips { get; set; }
        public virtual List List { get; set; }
    }
}
