//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperHandbook.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> MessageBoardId { get; set; }
        public Nullable<int> rating { get; set; }
        public string Comments { get; set; }
        public string Pubslier { get; set; }
    
        public virtual MessageBoard MessageBoard { get; set; }
    }
}
