//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperHandbook.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SuperDBEntities : DbContext
    {
        public SuperDBEntities()
            : base("name=SuperDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaseofOperation> BaseofOperations { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Creator> Creators { get; set; }
        public virtual DbSet<CurrentStatu> CurrentStatus { get; set; }
        public virtual DbSet<Equipment> Equipments { get; set; }
        public virtual DbSet<EquipPower> EquipPowers { get; set; }
        public virtual DbSet<Eye> Eyes { get; set; }
        public virtual DbSet<Issue> Issues { get; set; }
        public virtual DbSet<List> Lists { get; set; }
        public virtual DbSet<MartialStatu> MartialStatus { get; set; }
        public virtual DbSet<MessageBoard> MessageBoards { get; set; }
        public virtual DbSet<Occupation> Occupations { get; set; }
        public virtual DbSet<Power> Powers { get; set; }
        public virtual DbSet<SuperEquip> SuperEquips { get; set; }
        public virtual DbSet<SuperPower> SuperPowers { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<SuperTeam> SuperTeams { get; set; }
        public virtual DbSet<Superhero> Superheroes { get; set; }
    }
}
