//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperHandbook.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Power
    {
        public Power()
        {
            this.EquipPowers = new HashSet<EquipPower>();
            this.SuperPowers = new HashSet<SuperPower>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Comments { get; set; }
    
        public virtual ICollection<EquipPower> EquipPowers { get; set; }
        public virtual ICollection<SuperPower> SuperPowers { get; set; }
    }
}
