//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperHandbook.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuperPower
    {
        public int Id { get; set; }
        public int SuperheroId { get; set; }
        public int PowerId { get; set; }
    
        public virtual Power Power { get; set; }
        public virtual Superhero Superhero { get; set; }
    }
}
