//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperHandbook.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Superhero
    {
        public Superhero()
        {
            this.SuperEquips = new HashSet<SuperEquip>();
            this.SuperPowers = new HashSet<SuperPower>();
            this.SuperTeams = new HashSet<SuperTeam>();
        }
    
        public int Id { get; set; }
        public string RealName { get; set; }
        public string CodeName { get; set; }
        public Nullable<int> OccupationId { get; set; }
        public string Birthplace { get; set; }
        public Nullable<int> MartialstatusId { get; set; }
        public Nullable<int> BaseofOperationsId { get; set; }
        public string Origin { get; set; }
        public string height { get; set; }
        public Nullable<int> weight { get; set; }
        public byte[] Picture { get; set; }
        public string imagepath { get; set; }
        public Nullable<int> EyesId { get; set; }
        public Nullable<int> creatorId { get; set; }
        public Nullable<int> CurrentStatusId { get; set; }
        public Nullable<int> ListId { get; set; }
    
        public virtual BaseofOperation BaseofOperation { get; set; }
        public virtual Creator Creator { get; set; }
        public virtual CurrentStatu CurrentStatu { get; set; }
        public virtual Eye Eye { get; set; }
        public virtual MartialStatu MartialStatu { get; set; }
        public virtual Occupation Occupation { get; set; }
        public virtual ICollection<SuperEquip> SuperEquips { get; set; }
        public virtual ICollection<SuperPower> SuperPowers { get; set; }
        public virtual ICollection<SuperTeam> SuperTeams { get; set; }
        public virtual MessageBoard MessageBoard { get; set; }
        public virtual List List { get; set; }
    }
}
